language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t alexmarroquin/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alexmarroquin/docker-react npm run test